declare module "virtual:af-resume-entries" {
  import type * as Portable from "@doeixd/affe/Portable";

  /** Generated by the resume-extract Vite plugin; see the extract example. */
  export const resolverEntries: Portable.ResolverEntries;
}
